### ISSUE TITLE
uninitialized constant JWT

### ISSUE THREAD

**Issue by tylercollier** [gottfrois/grape-knock#1]
I got this error when running an RSpec test:

```
NameError:
       uninitialized constant JWT
     # ./spec/api/students_spec.rb:5:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # Grape::Knock::ForbiddenError:
     #   Grape::Knock::ForbiddenError
```

To fix, I had to `require 'jwt'` at the top of my grape API class. Is that expected? It's not mentioned in the README.

**Comment by gottfrois** [comment]
Issue probably comes from https://github.com/nsarno/knock since it uses JWT

**Comment by malagant** [comment]
I think this can be closed, as https://github.com/gottfrois/grape-knock/pull/2 has been merged.
