### ISSUE TITLE
Response to preflight request doesn't include 'Access-Control-Allow-Origin' header

### ISSUE THREAD

**Issue by n5ken** [gottfrois/grape-knock#6]
I am not sure if it's the problem from `Grape::Knock::Authenticable`, my front-end is a Vue project running on port 8080, and grape is on 3000. once I add `use Grape::Knock::Authenticable` in grape api, the browser print following error:

```ruby
Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 403.
```

I tried to add header manual but seems no effect

```ruby
module Depot
  class API < Grape::API
    version 'v1', using: :path
    format :json
    prefix :api

    before do
      header "Access-Control-Allow-Origin", "*"
      header "Access-Control-Allow-Headers", "Authorization, Content-Type"
      header "Access-Control-Allow-Methods", "GET, PUT, POST, DELETE, OPTIONS"
    end
```

Any idea?

`Affected version: 0.1.1`

**Comment by gottfrois** [comment]
I don't think it's related to the gem itself, you probably want to look at https://github.com/cyu/rack-cors

**Comment by n5ken** [comment]
It works, thanks! and looking forward to publish the latest code to support difference entity class. ;)

Cheers.
