### ISSUE TITLE
Update grape-knock in rubygems, please

### ISSUE THREAD

**Issue by nielsonrolim** [gottfrois/grape-knock#7]
The gem code in Rubygems is outdated. The last version is from August 20, 2015:

https://rubygems.org/gems/grape-knock/versions/0.1.1

Because of this, the current_user error is still happening:

NoMethodError (undefined method `current_user' for #<Knock::AuthToken:0x00000003977a40>):

**Comment by gottfrois** [comment]
released `v0.2.0` ;)
